#!/bin/bash

username=${1}
cluster_id=${2}
server_status=${3}
env_data=${4}
no_synch_nodes=$(echo $env_data | awk -F'|' '{print $1}')
no_nodes=$(echo $env_data | awk -F'|' '{print $2}')
no_open_alarms=$(echo $env_data | awk -F'|' '{print $3}')
enm_iso_version=$(echo $env_data | awk -F'|' '{print $4}')
nss_version=$(echo $env_data | awk -F'|' '{print $5}')
genstats_version=$(echo $env_data | awk -F'|' '{print $6}')
nss_utils_version=$(echo $env_data | awk -F'|' '{print $7}')
enm_torutils_version=$(echo $env_data | awk -F'|' '{print $8}')
enm_torutils_int_version=$(echo $env_data | awk -F'|' '{print $9}')
status_nagios=${5}
nagios_issues=${6}
other_issues=${7}
ticket_dashboard=${8}
tickets=${9}
supp_tickets=${10}
nrm_modules=${11}
ombs_bkps=${12}
mail_body=${13}

if [[ $server_status == *"AVAILABLE"* ]];then
  server_status_color="#0FC373"
fi

if [[ $server_status == *"DEGRADED"* ]];then
  server_status_color="#ff8c0a"
fi

if [[ $server_status == *"EXCLUSIVE"* ]];then
  server_status_color="#ff8c0a"
fi

if [[ $server_status == *"DEPLOYMENT ISSUES"* ]];then
  server_status_color="#ff3232"
fi

if [[ $server_status == *"MAINTENANCE ACTIVITIES"* ]];then
  server_status_color="#ff3232"
fi



cat <<_EOF >>$mail_body
<!DOCTYPE html>
<html lang="en">
 <body bgcolor="#E0E0E0" style="background-color:#E0E0E0;">
<table style="height: 527px; width: 600px; border-collapse: collapse;" border="0" align="center">
<tbody>
<tr>
<td style="text-align: left; padding: 0px 50px; background-color: #ffffff;">
<p>Report generated by Team Grifone ($username)</p>
</td></tr>
<tr>
<td style="text-align: center; background-color: $server_status_color; padding: 20px;">
<h3><strong><span style="color: #ffffff;">$clusterId $server_status</span></strong></h3>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 15px 50px 0px; text-align: left;">
<h4 style="margin: 0px; border-bottom:#a0a0a0 1px solid;"><strong>STATUS SUMMARY</strong> </h4>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;">Synchronized nodes: $no_synch_nodes ($no_nodes)</p>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;">Number open alarms: $no_open_alarms</p>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;"><strong>Main Issues:</strong></p>
_EOF


saveifs=$IFS
IFS="|"
if [[ $status_nagios == "true" ]];then
  for issue in $nagios_issues;do
    echo "<tr><td style=\"width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;\">" >>$mail_body
    echo "<p style=\"margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;\">$issue</p>" >>$mail_body
    echo "</td></tr>" >>$mail_body
  done
fi

for issue in $other_issues;do
  echo "<tr><td style=\"width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;\">" >>$mail_body
  echo "<p style=\"margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;\">$issue</p>" >>$mail_body
  echo "</td></tr>" >>$mail_body
done
IFS=$saveifs

cat <<_EOF >>$mail_body
<tr><td style="width: 498px; background-color: #ffffff; padding: 15px 50px 0px; text-align: left;">
<h4 style="margin: 0px; border-bottom:#a0a0a0 1px solid;"><a href="$ticket_dashboard"<strong>TICKETS DASHBOARD [ALL TICKETS]</strong></a></h4>
<tr><td style="width: 498px; background-color: #ffffff; padding: 15px 50px 0px; text-align: left;">
<h4 style="margin: 0px; border-bottom:#a0a0a0 1px solid;"><strong>TICKETS IN TESTING</strong></h4>
_EOF

saveifs=$IFS
IFS="@@"
for ticket in $tickets;do
ticket_url=$(echo $ticket | awk -F'|' '{print $1}')
ticket_descr=$(echo $ticket | awk -F'|' '{print $2}')
cat <<_EOF >>$mail_body
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px;"><a href="$ticket_url">$ticket_descr</a></p>
</td></tr>
_EOF
done
IFS=$saveifs

cat <<_EOF >>$mail_body
<tr><td style="width: 498px; background-color: #ffffff; padding: 15px 50px 0px; text-align: left;">
<h4 style="margin: 0px;"><strong>TICKETS FOR OPEN ISSUES</strong></h4>
</td></tr>
_EOF

saveifs=$IFS
IFS="@@"
for supp_ticket in $supp_tickets;do
supp_ticket_url=$(echo $supp_ticket | awk -F'|' '{print $1}')
supp_ticket_descr=$(echo $supp_ticket | awk -F'|' '{print $2}')
cat <<_EOF >>$mail_body
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px;"><a href="$supp_ticket_url">$supp_ticket_descr</a></p>
</td></tr>
_EOF
done
IFS=$saveifs

cat <<_EOF >>$mail_body
<tr><td style="width: 498px; background-color: #ffffff; padding: 15px 50px 0px; text-align: left;">
<h4 style="margin: 0px; border-bottom:#a0a0a0 1px solid;"><strong>GENERAL INFORMATION</strong></h4>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;"><strong>ENM ISO: </strong>$enm_iso_version</p>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;"><strong>NSS Simulations: </strong>$nss_version</p>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;"><strong>Genstats: </strong>$genstats_version</p>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;"><strong>NssUtils: </strong>$nss_utils_version</p>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;"><strong>TorUtils: </strong>$enm_torutils_version</p>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;"><strong>Internal TorUtils: </strong>$enm_torutils_int_version</p>
</td></tr>
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;"><strong>NRM Modules:</strong></p>
</td></tr>
_EOF

saveifs=$IFS
IFS="|"
for nrm_module in $nrm_modules;do
  echo "<tr><td style=\"width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;\">" >>$mail_body
  echo "<p style=\"margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;\">$nrm_module</p>" >>$mail_body
  echo "</td></tr>" >>$mail_body
done
IFS=$saveifs

cat <<_EOF >>$mail_body
<tr><td style="width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;">
<p style="margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;"><strong>OMBS Backup(s):</strong></p>
</td></tr>
_EOF

saveifs=$IFS
IFS="|"
for ombs_bkp in $ombs_bkps;do
  echo "<tr><td style=\"width: 498px; background-color: #ffffff; padding: 0px 50px; text-align: left;\">" >>$mail_body
  echo "<p style=\"margin: 0px; border-bottom:#a0a0a0 1px solid; border-color: #dfe2dd;\">$ombs_bkp</p>" >>$mail_body
  echo "</td></tr>" >>$mail_body
done
IFS=$saveifs

cat <<_EOF >>$mail_body
<tr><td style="padding: 10px 50px; background-color: #181818; color: #ffffff; text-align: center;">
<p>For more information please contact: <a href="mailto: PDLTEAMGRI@pdl.internal.ericsson.com">Team Grifone</a></p>
</td></tr>
</tbody>
</table>
</body>
</html>
_EOF
